### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [vlad2305m/Anaglyph-fabric#2]
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.minecraft.client.font.GlyphAtlasTexture.<init>(GlyphAtlasTexture:29)
	at net.minecraft.client.font.FontStorage.getGlyphRenderer(FontStorage:163)
	at net.minecraft.client.font.BuiltinEmptyGlyph.bake(BuiltinEmptyGlyph:53)
	at net.minecraft.client.font.FontStorage.setFonts(FontStorage:53)
	at net.minecraft.client.font.FontManager.method_27540(FontManager:45)
	at net.minecraft.util.Util.make(Util:440)
	at net.minecraft.client.font.FontManager.<init>(FontManager:45)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:540)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sternschnaube** [comment]
Thank you so much 🥳
Yes, sure - anr that's wonderful - I will never forget that LadyAgnes said „support for the next 50 years+“... 😱

But hoping for a better way in the future, between official update releases and mod developers 🙏🏿
